using System;

namespace PWD.CMS
{
    public enum PermissionType
    {
        None = 0,
        //AbpIdentityRoles = 1,
        //AbpIdentityRolesCreate = 2,
        //AbpIdentityRolesUpdate = 3,
        //AbpIdentityRolesDelete = 4,
        //AbpIdentityRolesManagePermissions = 5,
        //AbpIdentityUsers = 6,
        //AbpIdentityUsersCreate = 7,
        //AbpIdentityUsersUpdate = 8,
        //AbpIdentityUsersDelete = 9,
        //FeatureManagementManageHostFeatures = 10,
        //AbpIdentityUsersManagePermissions = 11,
        //SettingManagementEmailing = 12,
        //AbpTenantManagementTenants = 13,
        //AbpTenantManagementTenantsCreate = 14,
        //AbpTenantManagementTenantsUpdate = 15,
        //AbpTenantManagementTenantsDelete = 16,
        //AbpTenantManagementTenantsManageFeatures = 17,
        //AbpTenantManagementTenantsManageConnectionStrings = 18,
        Projects = 1,
        ProjectsCreate = 2,
        ProjectsEdit = 3,
        ProjectsDelete = 4,
        ProjectVariables=5,
        ProjectVariablesCreate = 6,
        ProjectVariablesEdit = 7,
        ProjectVariablesDelete = 8,
        ProjectAnalysisItems = 9,
        ProjectAnalysisItemsCreate = 10,
        ProjectAnalysisItemsEdit = 11,
        ProjectAnalysisItemsDelete = 12,
        CivilEstimates = 13,
        CivilEstimatesCreate = 14,
        CivilEstimatesOutput = 15,
        CivilReview = 16,
        CivilReviewOutput = 17,
        CivilReviewOTM = 18,
        CivilReviewLTM = 19,
        EMEstimates=20,
        EMEstimatesCreate=21,
        EMEstimatesOutput=22,
        EMReview=23,
        EMReviewOutput=24,
        EMReviewOTM=25,
        EMReviewLTM=26
    }

    public static class PermissionTypeExtension
    {
        public static string ToClaim(this PermissionType permissionType)
        {
            string strPermissionType = permissionType switch
            {
                //PermissionType.AbpIdentityRoles => "AbpIdentity.Roles",
                //PermissionType.AbpIdentityRolesCreate => "AbpIdentity.Roles.Create",
                //PermissionType.AbpIdentityRolesUpdate => "AbpIdentity.Roles.Update",
                //PermissionType.AbpIdentityRolesDelete => "AbpIdentity.Roles.Delete",
                //PermissionType.AbpIdentityRolesManagePermissions => "AbpIdentity.Roles.ManagePermissions",
                //PermissionType.AbpIdentityUsers => "AbpIdentity.Users",
                //PermissionType.AbpIdentityUsersCreate => "AbpIdentity.Users.Create",
                //PermissionType.AbpIdentityUsersUpdate => "AbpIdentity.Users.Update",
                //PermissionType.AbpIdentityUsersDelete => "AbpIdentity.Users.Delete",
                //PermissionType.FeatureManagementManageHostFeatures => "FeatureManagement.ManageHostFeatures",
                //PermissionType.AbpIdentityUsersManagePermissions => "AbpIdentity.Users.ManagePermissions",
                //PermissionType.SettingManagementEmailing => "SettingManagement.Emailing",
                //PermissionType.AbpTenantManagementTenants => "AbpTenantManagement.Tenants",
                //PermissionType.AbpTenantManagementTenantsCreate => "AbpTenantManagement.Tenants.Create",
                //PermissionType.AbpTenantManagementTenantsUpdate => "AbpTenantManagement.Tenants.Update",
                //PermissionType.AbpTenantManagementTenantsDelete => "AbpTenantManagement.Tenants.Delete",
                //PermissionType.AbpTenantManagementTenantsManageFeatures => "AbpTenantManagement.Tenants.ManageFeatures",
                //PermissionType.AbpTenantManagementTenantsManageConnectionStrings => "AbpTenantManagement.Tenants.ManageConnectionStrings",
                PermissionType.Projects => "PWDEstimate.Projects",
                PermissionType.ProjectsCreate => "PWDEstimate.Projects.Create",
                PermissionType.ProjectsEdit => "PWDEstimate.Projects.Edit",
                PermissionType.ProjectsDelete => "PWDEstimate.Projects.Delete",
                //PermissionType.ProjectVariables => "PWDEstimate.ProjectVariables",
                //PermissionType.ProjectVariablesCreate => "PWDEstimate.ProjectVariables.Create",
                //PermissionType.ProjectVariablesEdit => "PWDEstimate.ProjectVariables.Edit",
                //PermissionType.ProjectVariablesDelete => "PWDEstimate.ProjectVariables.Delete",
                PermissionType.ProjectAnalysisItems => "PWDEstimate.ProjectAnalysisItems",
                PermissionType.ProjectAnalysisItemsCreate => "PWDEstimate.ProjectAnalysisItems.Create",
                PermissionType.ProjectAnalysisItemsEdit => "PWDEstimate.ProjectAnalysisItems.Edit",
                PermissionType.ProjectAnalysisItemsDelete => "PWDEstimate.ProjectAnalysisItems.Delete",
                PermissionType.CivilEstimates => "PWDEstimate.CivilEstimates",
                PermissionType.CivilEstimatesCreate => "PWDEstimate.CivilEstimates.Create",
                PermissionType.CivilEstimatesOutput => "PWDEstimate.CivilEstimates.PopulateOutput",
                PermissionType.CivilReview => "PWDEstimate.CivilReview",
                PermissionType.CivilReviewOutput => "PWDEstimate.CivilReview.PopulateOutput",
                PermissionType.CivilReviewOTM => "PWDEstimate.CivilReview.OTM",
                PermissionType.CivilReviewLTM => "PWDEstimate.CivilReview.LTM",
                PermissionType.EMEstimates => "PWDEstimate.EMEstimates",
                PermissionType.EMEstimatesCreate => "PWDEstimate.EMEstimates.Create",
                PermissionType.EMEstimatesOutput => "PWDEstimate.EMEstimates.PopulateOutput",
                PermissionType.EMReview => "PWDEstimate.EMReview",
                PermissionType.EMReviewOutput => "PWDEstimate.EMReview.PopulateOutput",
                PermissionType.EMReviewOTM => "PWDEstimate.EMReview.OTM",
                PermissionType.EMReviewLTM => "PWDEstimate.EMReview.LTM",
                _ => throw new NotImplementedException($"Permission type - '{permissionType}' is not implemented."),
            };
            return strPermissionType;
        }
    }
}
